# Generated by Django 3.0.8 on 2020-08-07 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('explain', models.TextField()),
                ('look', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='playlistProfile/')),
                ('like', models.ManyToManyField(blank=True, related_name='playlist_likes', to=settings.AUTH_USER_MODEL)),
                ('putIn', models.ManyToManyField(blank=True, related_name='playlist_putIn', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_wirter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('time', models.DurationField()),
                ('albumArt', models.ImageField(upload_to='albumArt/')),
                ('melonUid', models.IntegerField()),
                ('genieUid', models.IntegerField()),
                ('bugsUid', models.IntegerField()),
                ('floUid', models.CharField(max_length=200)),
                ('viveUid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('playlistObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relate_to_playlist', to='playlistApp.Playlist')),
                ('songObj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relate_to_song', to='playlistApp.Song')),
            ],
        ),
    ]
