# Generated by Django 3.0.7 on 2020-08-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='look',
            field=models.IntegerField(default=0),
        ),
    ]
