# Generated by Django 3.0.7 on 2020-08-06 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistApp', '0002_auto_20200806_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='time',
            field=models.DurationField(),
        ),
    ]
