# Generated by Django 3.0.7 on 2020-08-06 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlistApp', '0003_auto_20200806_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='likes',
            field=models.ManyToManyField(default=True, related_name='playlist_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='putIn',
            field=models.ManyToManyField(default=True, related_name='playlist_putIn', to=settings.AUTH_USER_MODEL),
        ),
    ]
