# Generated by Django 3.0.7 on 2020-08-06 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlistApp', '0004_auto_20200806_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='likes',
        ),
        migrations.AddField(
            model_name='playlist',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='playlist_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='putIn',
            field=models.ManyToManyField(blank=True, related_name='playlist_putIn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_wirter', to=settings.AUTH_USER_MODEL),
        ),
    ]
