# Generated by Django 3.0.8 on 2020-08-07 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicServiceAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_service_code', models.IntegerField(choices=[(1, 'Melon'), (2, 'Genie'), (3, 'Flo'), (4, 'Vibe'), (5, 'Bugs')])),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('follow', models.ManyToManyField(related_name='follow', to=settings.AUTH_USER_MODEL)),
                ('primaryMusicAccount', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snsApp.MusicServiceAccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='musicserviceaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerMusicAccount', to='snsApp.Profile'),
        ),
    ]
