# Generated by Django 3.0.8 on 2020-08-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snsApp', '0002_auto_20200808_0428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicserviceaccount',
            old_name='music_service_code',
            new_name='music_provider',
        ),
    ]
