# Generated by Django 3.0.8 on 2020-08-29 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlistApp', '0002_auto_20200829_1602'),
        ('snsApp', '0003_auto_20200808_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='music',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='playlistApp.Song'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primaryMusicAccount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snsApp.MusicServiceAccount'),
        ),
    ]
